# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-26 16:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 26, 16, 17, 20, 650409)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2016, 10, 26, 16, 17, 20, 650357)),
        ),
    ]
