# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-19 17:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_auto_20161019_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 19, 17, 31, 17, 742014)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2016, 10, 19, 17, 31, 17, 741964)),
        ),
    ]
